# Generated by Django 5.1.3 on 2024-11-15 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('HoanThanh', models.BooleanField(default=False, null=True)),
                ('MaGiaoDich', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=200, null=True)),
                ('gia', models.FloatField()),
                ('SoLuong', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaChiGiaoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(blank=True, default=0, null=True)),
                ('DiaChi', models.CharField(max_length=200, null=True)),
                ('ThanhPho', models.CharField(max_length=200, null=True)),
                ('Tinh', models.CharField(max_length=200, null=True)),
                ('SDT', models.CharField(max_length=200, null=True)),
                ('NgayThem', models.DateTimeField(auto_now_add=True)),
                ('DatHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dathang')),
                ('KhachHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachhang')),
            ],
        ),
        migrations.AddField(
            model_name='dathang',
            name='KhachHang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachhang'),
        ),
        migrations.CreateModel(
            name='SP_da_DatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(blank=True, default=0, null=True)),
                ('NgayThem', models.DateTimeField(auto_now_add=True)),
                ('DatHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dathang')),
                ('SanPham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sanpham')),
            ],
        ),
    ]
