# Generated by Django 5.1.3 on 2024-11-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sanpham_hinhanh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dathang',
            old_name='KhachHang',
            new_name='khachHang',
        ),
    ]
